dist: bionic
# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.6"
  - "3.7"
  - "3.8"
# allow gui output
services:
  - xvfb
before_install:
  # install some renderers
  # check version
  - lsb_release -a
install:
  - echo $USER
# command to run tests
script:
# command to install dependencies
  - ./install
# command to pull and run Dgraph
# switch off due to https://discuss.dgraph.io/t/dgraph-v20-07-0-v20-03-0-unreliability-in-mac-os-environment/9376
  # pull dgraph
  - scripts/dgraph -p
  # run dgraph
  - scripts/dgraph
  # run jena tdbloader
  - scripts/crjena
  # run jena fuseki server
  - scripts/jena -f cr
# command to get sample data
  - scripts/getsamples
# command to run tests
  - ./test
