#!/bin/bash
# WF 2020-07-17
# get proceedings xml nodes from dblp xml download
xml=$HOME/downloads/dblp.xml
tmpxml=/tmp/proceedings-dblp.xml
json=sampledata/dblp.json
head -3 $xml > $tmpxml
# make sure there are newlines before and after end tags
# of type proceeding with sed and then filter with awk
# https://stackoverflow.com/a/24707372/1497139
cat $xml | sed $'s/<proceedings/\\\n&/g' | sed $'s/<.proceedings>/&\\\n/g' | awk '
# select proceedings nodes (which should be clearly separated by now)
/<proceedings/,/<\/proceedings>/ {
  print
}' >> $tmpxml
echo "</dblp>" >> $tmpxml
xq . $tmpxml > $json
