#!/bin/bash
# WF 2020-07-07

# check that sphinx-apidoc is installed
checkinstalled() {
  local l_cmd="$1"
  which $l_cmd > /dev/null
  if [ $? -ne 0 ]
  then
    echo "$l_cmd need to be installed" 1>&2
    exit 1
  fi
}

#
# quickstart the sphinx documentation
#
quickstart() {
  local l_project="$1"
  sphinx-quickstart --ext-autodoc -p "$l_project"
}

checkinstalled  sphinx-apidoc
if [ ! -d docs ]
then
  echo "no docs directory yet - will use sphinx quickstart to create"
  quickstart ProceedingsTitleParser
fi
sphinx-apidoc -f -o docs/source . ptp plots storage
cd docs
make clean html
open build/html/index.html
