#!/bin/bash
# WF 2020-03-25
os=$(uname -a)
case $os in
  Darwin*)
   pip="sudo -H pip"
   install="sudo port install"
   ;;
  *)
   pip="pip3"
   if [ "$USER" = "travis" ]
   then
     # https://stackoverflow.com/a/20621143/1497139
     echo "environment is travis with python version $TRAVIS_PYTHON_VERSION"
     pip="pip"
   fi
   install="sudo apt-get install"
   ;;
esac
#$install python3-pip
$pip --version
echo "installing required python modules"
$pip install --user -r requirements.txt

wd=$(pwd)
if [ ! -d web ]
then
  echo "installing needed web files from diagrams.bitplan.com project"
  tmp=/tmp
  cd $tmp
  git clone https://github.com/BITPlan/diagrams
  mv $tmp/diagrams/web $wd/web
  rm -rf /tmp/diagrams
  cd $wd
else
  echo "need web files already installed"
fi
