#!/bin/bash
# WF 2020-03-25
os=$(uname -a)
useroption="--user"
case $os in
  Darwin*)
   pip="sudo -H pip"
   install="sudo port install"
   ;;
  *)
   pip="pip3"
   if [ "$USER" = "travis" ]
   then
     # https://stackoverflow.com/a/20621143/1497139
     echo "environment is travis with python version $TRAVIS_PYTHON_VERSION"
     pip="pip"
     useroption=""
   fi
   install="sudo apt-get install"
   ;;
esac
#$install python3-pip
$pip --version
echo "installing required python modules with useroption $useroption"
$pip install $useroption -r requirements.txt

wd=$(pwd)
if [ ! -d web ]
then
  echo "installing needed web files from diagrams.bitplan.com project"
  tmp=/tmp
  cd $tmp
  git clone https://github.com/BITPlan/diagrams
  mv $tmp/diagrams/web $wd/web
  rm -rf /tmp/diagrams
  cd $wd
else
  echo "need web files already installed"
fi

# make sure pywikibot configuration is available
if [ ! -d $HOME/.pywikibot ]
then  
   mkdir $HOME/.pywikibot
   echo "creating user-config.py"
   echo "put_throttle = 0" > $HOME/.pywikibot/user-config.py
fi
